# Refs:
# - https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics
# - https://docs.projectcalico.org/security/comms/secure-metrics
# - https://docs.projectcalico.org/reference/kube-controllers/prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: calico-node-metrics
  namespace: calico-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    k8s-app: calico-node
  ports:
  - name: metrics-port
    port: 9091
    targetPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: calico-typha-metrics
  namespace: calico-system
  labels:
    k8s-app: calico-typha
spec:
  selector:
    k8s-app: calico-typha
  ports:
  - name: metrics-port
    port: 9091
    targetPort: 9091
