---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  auth:
    strategy: token
  deployment:
    accessible_namespaces:
    - '**'
    ingress:
      enabled: false
  external_services:
    custom_dashboards:
      namespace_label: namespace
    grafana:
      auth:
        insecure_skip_verify: true
        type: basic
        username: admin
        password: secret:kiali-user:password
      in_cluster_url: http://grafana.metrics-system:3000
      url: http://grafana.mycluster.mydomain
    prometheus:
      is_core: false
      url: http://prometheus-k8s.metrics-system:9090
    tracing:
      enabled: false
