---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-production
spec:
  acme:
    email: myemail@mydomain
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-production-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.mycluster.mydoamin
          solverName: infoblox-wapi
          config:
            host: myinfobloxhost
            view: DNS
            usernameSecretRef:
              name: infoblox-credentials
              key: username
            passwordSecretRef:
              name: infoblox-credentials
              key: password
