---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycluster-ingress-cert
  namespace: istio-gateways
spec:
  secretName: mycluster-ingress-cert-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: le-production
    kind: ClusterIssuer
  dnsNames:
  - mycluster.mydomain
  - '*.mycluster.mydomain'
