apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infoblox-wapi-test
  namespace: cert-manager-test
spec:
  secretName: infoblox-wapi-test-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: le-staging
    kind: ClusterIssuer
  dnsNames:
  - cert-manager-test.mycluster.mydomain
